# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TopographyMapper
                                 A QGIS plugin
 Generates Topography Map from Copernicus 30m DEM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-18
        copyright            : (C) 2025 by Ravikant
        email                : ravikant.ncs@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TopographyMapper class from file TopographyMapper.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Topography_Mapping_Tool import TopographyMapper
    return TopographyMapper(iface)
